version: "3.9"
services:
  db:
    image: postgres:15
    container_name: unified_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: unified_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pg_network
volumes:
  postgres_data:
networks:
  pg_network:
